apiVersion: v1
kind: Service
metadata:
  name: projectmanager-api
  namespace: backend
spec:
  selector:
    app: projectmanager-api
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001 
