apiVersion: v1
kind: Service
metadata:
  name: projectmanager-api-service
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: projectmanager-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
