apiVersion: v1
kind: Service
metadata:
  name: projectmanager-ui-service
  namespace: frontend
spec:
  selector:
    app: projectmanager-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
